### PR TITLE
Slugs should never end with a substitution character

### PR DESCRIPTION
**Pull request by jordanbyron**
Currently it is possible for generated slugs to end with a substitution character when `max_length` is set. That results in nasty looking slugs, and eventually urls. This tiny patch ensures any trailing substitution characters are removed.

### CODE REVIEW

**Comment by jordanbyron** [comment]
@sfaxon have you had a chance to look at this?

**Comment by sfaxon** [comment]
Sorry for the delay, this fell off my inbox.  I'll roll a new version now too.

**Comment by jordanbyron** [comment]
No worries. I know we are all busy :smile: Thanks for merging this!

**Comment by sfaxon** [comment]
0.3.1 should be up on rubygems.

**Pull request merged**
